<?php

namespace Database\Seeders;

use App\Models\Booking;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class BookingSeeder extends Seeder
{
    public function run()
    {
        for ($i = 1; $i <= 10; $i++) {
            Booking::create([
                'user_id' => random_int(1, 5), // Replace with actual user IDs from UserSeeder
                'court_id' => random_int(1, 10), // Replace with Court IDs
                'start_time' => Carbon::now()->addDays(random_int(1, 30))->toDateTimeString(),
                'duration' => random_int(1, 3),
                'status' => 'confirmed',
                'notes' => 'Booking generated by seeder',
            ]);
        }
    }
}
